
default_context:
    bitbucket_repo: "vexmpp"
    bitbucket_url: "https://bitbucket.org/bitbucket-user/vexmpp"
    bitbucket_username: "bitbucket-user"
    default_locale: "en_US"
    email: "travis@pobox.com"
    full_name: "Travis Shirk"
    gettext_domain: "None"
    github_repo: "vexmpp"
    github_url: "https://github.com/nicfit/vexmpp"
    github_username: "nicfit"
    intended_audience: "Developers"
    license: "MIT"
    project_long_description: ""
    project_name: "vexmpp"
    project_short_description: "XMPP library for Python3 asyncio."
    project_slug: "vexmpp"
    py26: "no"
    py27: "no"
    py33: "no"
    py34: "no"
    py35: "no"
    py36: "yes"
    py37: "yes"
    py_module: "vexmpp"
    pyapp_type: "asyncio"
    pypi_repo_name: "vexmpp"
    pypi_username: "nicfit"
    release_date: "today"
    src_dir: "."
    use_bitbucket: "no"
    use_github: "yes"
    use_make: "yes"
    use_paver: "no"
    use_pypi_deployment_with_travis: "no"
    use_pytest: "yes"
    use_rtd: "no"
    use_travis_ci: "yes"
    version: "0.1.0"
    web: "https://github.com/nicfit/vexmpp"
    year: "2014-2017"
